/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'studentId' : IDL.Nat,
  'note' : IDL.Text,
  'year' : IDL.Nat,
  'paymentType' : IDL.Text,
  'amount' : IDL.Float64,
  'paidAt' : IDL.Int,
  'receiptNumber' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'rollNumber' : IDL.Text,
  'phone' : IDL.Text,
  'monthlyFee' : IDL.Float64,
  'className' : IDL.Text,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPayment' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createExpense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
  'getExpensesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getExpensesByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesByMonthYearTotal' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Float64],
      ['query'],
    ),
  'getFeesByMonthYear' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
  'getPaymentsByMonthYear' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Payment)],
      ['query'],
    ),
  'getPaymentsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'getPendingFeeStudents' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
  'getTotalExpenses' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalFeesCollected' : IDL.Func([], [IDL.Float64], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateStudent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'studentId' : IDL.Nat,
    'note' : IDL.Text,
    'year' : IDL.Nat,
    'paymentType' : IDL.Text,
    'amount' : IDL.Float64,
    'paidAt' : IDL.Int,
    'receiptNumber' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'rollNumber' : IDL.Text,
    'phone' : IDL.Text,
    'monthlyFee' : IDL.Float64,
    'className' : IDL.Text,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPayment' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createExpense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deleteExpense' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteStudent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [IDL.Opt(Expense)], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByMonthYearTotal' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Float64],
        ['query'],
      ),
    'getFeesByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Float64],
        ['query'],
      ),
    'getPaymentsByMonthYear' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'getPaymentsByStudent' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
    'getPendingFeeStudents' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getStudent' : IDL.Func([IDL.Nat], [IDL.Opt(Student)], ['query']),
    'getTotalExpenses' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalFeesCollected' : IDL.Func([], [IDL.Float64], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateStudent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };