/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Expense {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface Payment {
  'id' : bigint,
  'month' : bigint,
  'studentId' : bigint,
  'note' : string,
  'year' : bigint,
  'paymentType' : string,
  'amount' : number,
  'paidAt' : bigint,
  'receiptNumber' : string,
}
export interface Student {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'rollNumber' : string,
  'phone' : string,
  'monthlyFee' : number,
  'className' : string,
  'parentName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPayment' : ActorMethod<
    [bigint, number, string, bigint, bigint, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExpense' : ActorMethod<[string, string, number, string], bigint>,
  'createStudent' : ActorMethod<
    [string, string, string, string, string, number],
    bigint
  >,
  'deleteExpense' : ActorMethod<[bigint], boolean>,
  'deleteStudent' : ActorMethod<[bigint], boolean>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpense' : ActorMethod<[bigint], [] | [Expense]>,
  'getExpensesByCategory' : ActorMethod<[string], Array<Expense>>,
  'getExpensesByMonthYear' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getExpensesByMonthYearTotal' : ActorMethod<[bigint, bigint], number>,
  'getFeesByMonthYear' : ActorMethod<[bigint, bigint], number>,
  'getPaymentsByMonthYear' : ActorMethod<[bigint, bigint], Array<Payment>>,
  'getPaymentsByStudent' : ActorMethod<[bigint], Array<Payment>>,
  'getPendingFeeStudents' : ActorMethod<[bigint, bigint], Array<Student>>,
  'getStudent' : ActorMethod<[bigint], [] | [Student]>,
  'getTotalExpenses' : ActorMethod<[], number>,
  'getTotalFeesCollected' : ActorMethod<[], number>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateExpense' : ActorMethod<
    [bigint, string, string, number, string],
    boolean
  >,
  'updateStudent' : ActorMethod<
    [bigint, string, string, string, string, string, number],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];